CREATE TABLE [dbo].[contact] (
    [Id]                                 UNIQUEIDENTIFIER NOT NULL,
    [SinkCreatedOn]                      DATETIME         NULL,
    [SinkModifiedOn]                     DATETIME         NULL,
    [statecode]                          INT              NULL,
    [statuscode]                         INT              NULL,
    [address1_shippingmethodcode]        INT              NULL,
    [address2_shippingmethodcode]        INT              NULL,
    [msdyn_orgchangestatus]              INT              NULL,
    [familystatuscode]                   INT              NULL,
    [address1_freighttermscode]          INT              NULL,
    [address2_addresstypecode]           INT              NULL,
    [shippingmethodcode]                 INT              NULL,
    [preferredappointmenttimecode]       INT              NULL,
    [preferredcontactmethodcode]         INT              NULL,
    [address1_addresstypecode]           INT              NULL,
    [address3_freighttermscode]          INT              NULL,
    [dfeta_title]                        INT              NULL,
    [territorycode]                      INT              NULL,
    [accountrolecode]                    INT              NULL,
    [dfeta_addressverificationflag]      INT              NULL,
    [dfeta_inductionstatus]              INT              NULL,
    [address2_freighttermscode]          INT              NULL,
    [haschildrencode]                    INT              NULL,
    [gendercode]                         INT              NULL,
    [customertypecode]                   INT              NULL,
    [educationcode]                      INT              NULL,
    [address3_shippingmethodcode]        INT              NULL,
    [customersizecode]                   INT              NULL,
    [paymenttermscode]                   INT              NULL,
    [address3_addresstypecode]           INT              NULL,
    [dfeta_suppressionflag]              INT              NULL,
    [preferredappointmentdaycode]        INT              NULL,
    [leadsourcecode]                     INT              NULL,
    [isbackofficecustomer]               BIT              NULL,
    [merged]                             BIT              NULL,
    [donotfax]                           BIT              NULL,
    [followemail]                        BIT              NULL,
    [donotemail]                         BIT              NULL,
    [isautocreate]                       BIT              NULL,
    [donotpostalmail]                    BIT              NULL,
    [dfeta_addressconsent]               BIT              NULL,
    [isprivate]                          BIT              NULL,
    [dfeta_activesanctions]              BIT              NULL,
    [donotbulkemail]                     BIT              NULL,
    [dfeta_disability]                   BIT              NULL,
    [donotsendmm]                        BIT              NULL,
    [donotphone]                         BIT              NULL,
    [creditonhold]                       BIT              NULL,
    [marketingonly]                      BIT              NULL,
    [donotbulkpostalmail]                BIT              NULL,
    [dfeta_trnrequired]                  BIT              NULL,
    [participatesinworkflow]             BIT              NULL,
    [msdyn_gdproptout]                   BIT              NULL,
    [originatingleadid]                  UNIQUEIDENTIFIER NULL,
    [originatingleadid_entitytype]       NVARCHAR (128)   NULL,
    [dfeta_nationalityid]                UNIQUEIDENTIFIER NULL,
    [dfeta_nationalityid_entitytype]     NVARCHAR (128)   NULL,
    [parentcontactid]                    UNIQUEIDENTIFIER NULL,
    [parentcontactid_entitytype]         NVARCHAR (128)   NULL,
    [defaultpricelevelid]                UNIQUEIDENTIFIER NULL,
    [defaultpricelevelid_entitytype]     NVARCHAR (128)   NULL,
    [accountid]                          UNIQUEIDENTIFIER NULL,
    [accountid_entitytype]               NVARCHAR (128)   NULL,
    [slaid]                              UNIQUEIDENTIFIER NULL,
    [slaid_entitytype]                   NVARCHAR (128)   NULL,
    [slainvokedid]                       UNIQUEIDENTIFIER NULL,
    [slainvokedid_entitytype]            NVARCHAR (128)   NULL,
    [preferredserviceid]                 UNIQUEIDENTIFIER NULL,
    [preferredserviceid_entitytype]      NVARCHAR (128)   NULL,
    [owninguser]                         UNIQUEIDENTIFIER NULL,
    [owninguser_entitytype]              NVARCHAR (128)   NULL,
    [preferredsystemuserid]              UNIQUEIDENTIFIER NULL,
    [preferredsystemuserid_entitytype]   NVARCHAR (128)   NULL,
    [parent_contactid]                   UNIQUEIDENTIFIER NULL,
    [parent_contactid_entitytype]        NVARCHAR (128)   NULL,
    [dfeta_disabilityid]                 UNIQUEIDENTIFIER NULL,
    [dfeta_disabilityid_entitytype]      NVARCHAR (128)   NULL,
    [createdby]                          UNIQUEIDENTIFIER NULL,
    [createdby_entitytype]               NVARCHAR (128)   NULL,
    [owningteam]                         UNIQUEIDENTIFIER NULL,
    [owningteam_entitytype]              NVARCHAR (128)   NULL,
    [modifiedbyexternalparty]            UNIQUEIDENTIFIER NULL,
    [modifiedbyexternalparty_entitytype] NVARCHAR (128)   NULL,
    [createdbyexternalparty]             UNIQUEIDENTIFIER NULL,
    [createdbyexternalparty_entitytype]  NVARCHAR (128)   NULL,
    [owningbusinessunit]                 UNIQUEIDENTIFIER NULL,
    [owningbusinessunit_entitytype]      NVARCHAR (128)   NULL,
    [modifiedonbehalfby]                 UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfby_entitytype]      NVARCHAR (128)   NULL,
    [dfeta_qtsregistrationid]            UNIQUEIDENTIFIER NULL,
    [dfeta_qtsregistrationid_entitytype] NVARCHAR (128)   NULL,
    [transactioncurrencyid]              UNIQUEIDENTIFIER NULL,
    [transactioncurrencyid_entitytype]   NVARCHAR (128)   NULL,
    [modifiedby]                         UNIQUEIDENTIFIER NULL,
    [modifiedby_entitytype]              NVARCHAR (128)   NULL,
    [dfeta_ethnicityid]                  UNIQUEIDENTIFIER NULL,
    [dfeta_ethnicityid_entitytype]       NVARCHAR (128)   NULL,
    [masterid]                           UNIQUEIDENTIFIER NULL,
    [masterid_entitytype]                NVARCHAR (128)   NULL,
    [createdonbehalfby]                  UNIQUEIDENTIFIER NULL,
    [createdonbehalfby_entitytype]       NVARCHAR (128)   NULL,
    [preferredequipmentid]               UNIQUEIDENTIFIER NULL,
    [preferredequipmentid_entitytype]    NVARCHAR (128)   NULL,
    [ownerid]                            UNIQUEIDENTIFIER NULL,
    [ownerid_entitytype]                 NVARCHAR (128)   NULL,
    [parentcustomerid]                   UNIQUEIDENTIFIER NULL,
    [parentcustomerid_entitytype]        NVARCHAR (128)   NULL,
    [aging60]                            DECIMAL (38, 2)  NULL,
    [creditlimit_base]                   DECIMAL (38, 4)  NULL,
    [aging30]                            DECIMAL (38, 2)  NULL,
    [aging30_base]                       DECIMAL (38, 4)  NULL,
    [annualincome]                       DECIMAL (38, 2)  NULL,
    [aging90_base]                       DECIMAL (38, 4)  NULL,
    [creditlimit]                        DECIMAL (38, 2)  NULL,
    [aging60_base]                       DECIMAL (38, 4)  NULL,
    [aging90]                            DECIMAL (38, 2)  NULL,
    [annualincome_base]                  DECIMAL (38, 4)  NULL,
    [overriddencreatedon]                DATETIME         NULL,
    [dfeta_capitaninumberchangedon]      DATETIME         NULL,
    [dfeta_emailaddresslastupdated]      DATETIME         NULL,
    [createdbyexternalpartyyominame]     NVARCHAR (100)   NULL,
    [dfeta_eytsdatechangedon]            DATETIME         NULL,
    [address2_telephone3]                NVARCHAR (50)    NULL,
    [teamsfollowed]                      INT              NULL,
    [dfeta_previousemail]                NVARCHAR (200)   NULL,
    [address2_upszone]                   NVARCHAR (4)     NULL,
    [createdonbehalfbyyominame]          NVARCHAR (100)   NULL,
    [parentcustomeridtype]               NVARCHAR (4000)  NULL,
    [parentcustomeridyominame]           NVARCHAR (450)   NULL,
    [pager]                              NVARCHAR (50)    NULL,
    [mobilephone]                        NVARCHAR (60)    NULL,
    [dfeta_capitadateofbirthchangedon]   DATETIME         NULL,
    [accountidyominame]                  NVARCHAR (100)   NULL,
    [numberofchildren]                   INT              NULL,
    [mastercontactidyominame]            NVARCHAR (100)   NULL,
    [address2_stateorprovince]           NVARCHAR (50)    NULL,
    [createdbyyominame]                  NVARCHAR (100)   NULL,
    [address2_line3]                     NVARCHAR (250)   NULL,
    [assistantname]                      NVARCHAR (100)   NULL,
    [address2_latitude]                  DECIMAL (38, 5)  NULL,
    [fax]                                NVARCHAR (60)    NULL,
    [exchangerate]                       DECIMAL (38, 10) NULL,
    [managerphone]                       NVARCHAR (50)    NULL,
    [dfeta_sauserid]                     NVARCHAR (20)    NULL,
    [address1_line3]                     NVARCHAR (250)   NULL,
    [telephone3]                         NVARCHAR (50)    NULL,
    [address3_utcoffset]                 INT              NULL,
    [transactioncurrencyidname]          NVARCHAR (100)   NULL,
    [managername]                        NVARCHAR (100)   NULL,
    [address1_telephone3]                NVARCHAR (50)    NULL,
    [address2_name]                      NVARCHAR (100)   NULL,
    [address3_postofficebox]             NVARCHAR (20)    NULL,
    [owningbusinessunitname]             NVARCHAR (160)   NULL,
    [onholdtime]                         INT              NULL,
    [dfeta_contactnumberlastupdated]     DATETIME         NULL,
    [dfeta_qtsregistrationidname]        NVARCHAR (250)   NULL,
    [childrensnames]                     NVARCHAR (255)   NULL,
    [address1_postalcode]                NVARCHAR (20)    NULL,
    [businesscard]                       NVARCHAR (MAX)   NULL,
    [address1_line1]                     NVARCHAR (250)   NULL,
    [department]                         NVARCHAR (100)   NULL,
    [createdbyexternalpartyname]         NVARCHAR (100)   NULL,
    [address3_county]                    NVARCHAR (50)    NULL,
    [preferredequipmentidname]           NVARCHAR (100)   NULL,
    [dfeta_qtsdatechangedon]             DATETIME         NULL,
    [dfeta_trn]                          NVARCHAR (50)    NULL,
    [modifiedbyyominame]                 NVARCHAR (100)   NULL,
    [address3_line1]                     NVARCHAR (250)   NULL,
    [address2_country]                   NVARCHAR (80)    NULL,
    [traversedpath]                      NVARCHAR (1250)  NULL,
    [address3_telephone1]                NVARCHAR (50)    NULL,
    [address3_telephone2]                NVARCHAR (50)    NULL,
    [address3_telephone3]                NVARCHAR (50)    NULL,
    [address1_county]                    NVARCHAR (50)    NULL,
    [owneridyominame]                    NVARCHAR (100)   NULL,
    [dfeta_mergeinfo]                    NVARCHAR (100)   NULL,
    [defaultpricelevelidname]            NVARCHAR (100)   NULL,
    [websiteurl]                         NVARCHAR (200)   NULL,
    [modifiedbyname]                     NVARCHAR (100)   NULL,
    [mastercontactidname]                NVARCHAR (100)   NULL,
    [entityimageid]                      UNIQUEIDENTIFIER NULL,
    [address3_line3]                     NVARCHAR (250)   NULL,
    [address3_country]                   NVARCHAR (80)    NULL,
    [address2_telephone1]                NVARCHAR (50)    NULL,
    [address2_telephone2]                NVARCHAR (50)    NULL,
    [modifiedonbehalfbyname]             NVARCHAR (100)   NULL,
    [parentcustomeridname]               NVARCHAR (160)   NULL,
    [emailaddress2]                      NVARCHAR (100)   NULL,
    [utcconversiontimezonecode]          INT              NULL,
    [employeeid]                         NVARCHAR (50)    NULL,
    [address3_composite]                 NVARCHAR (MAX)   NULL,
    [dfeta_previouslastname]             NVARCHAR (50)    NULL,
    [birthdate]                          DATETIME         NULL,
    [address1_primarycontactname]        NVARCHAR (100)   NULL,
    [address1_utcoffset]                 INT              NULL,
    [createdon]                          DATETIME         NULL,
    [address1_longitude]                 DECIMAL (38, 5)  NULL,
    [yomifullname]                       NVARCHAR (450)   NULL,
    [telephone2]                         NVARCHAR (60)    NULL,
    [address2_longitude]                 DECIMAL (38, 5)  NULL,
    [address2_line1]                     NVARCHAR (250)   NULL,
    [address2_city]                      NVARCHAR (80)    NULL,
    [callback]                           NVARCHAR (50)    NULL,
    [emailaddress3]                      NVARCHAR (100)   NULL,
    [address3_stateorprovince]           NVARCHAR (50)    NULL,
    [emailaddress1]                      NVARCHAR (100)   NULL,
    [owneridtype]                        NVARCHAR (4000)  NULL,
    [address1_fax]                       NVARCHAR (50)    NULL,
    [preferredsystemuseridname]          NVARCHAR (100)   NULL,
    [address3_addressid]                 UNIQUEIDENTIFIER NULL,
    [address2_primarycontactname]        NVARCHAR (100)   NULL,
    [dfeta_hlta_candidate_id]            NVARCHAR (20)    NULL,
    [dfeta_dateofdeath]                  DATETIME         NULL,
    [ftpsiteurl]                         NVARCHAR (200)   NULL,
    [dfeta_disabilityidname]             NVARCHAR (250)   NULL,
    [address2_postofficebox]             NVARCHAR (20)    NULL,
    [address3_line2]                     NVARCHAR (250)   NULL,
    [parent_contactidyominame]           NVARCHAR (450)   NULL,
    [dfeta_loginfailedcounter]           INT              NULL,
    [processid]                          UNIQUEIDENTIFIER NULL,
    [address3_fax]                       NVARCHAR (50)    NULL,
    [subscriptionid]                     UNIQUEIDENTIFIER NULL,
    [address2_addressid]                 UNIQUEIDENTIFIER NULL,
    [governmentid]                       NVARCHAR (50)    NULL,
    [business2]                          NVARCHAR (50)    NULL,
    [middlename]                         NVARCHAR (100)   NULL,
    [address1_city]                      NVARCHAR (80)    NULL,
    [slaname]                            NVARCHAR (100)   NULL,
    [originatingleadidyominame]          NVARCHAR (100)   NULL,
    [entityimage_timestamp]              BIGINT           NULL,
    [modifiedon]                         DATETIME         NULL,
    [versionnumber]                      BIGINT           NULL,
    [jobtitle]                           NVARCHAR (100)   NULL,
    [preferredserviceidname]             NVARCHAR (100)   NULL,
    [dfeta_trnallocaterequest]           DATETIME         NULL,
    [dfeta_tssupdate]                    DATETIME         NULL,
    [address3_upszone]                   NVARCHAR (4)     NULL,
    [address3_city]                      NVARCHAR (80)    NULL,
    [yomilastname]                       NVARCHAR (150)   NULL,
    [address3_latitude]                  DECIMAL (38, 5)  NULL,
    [address1_composite]                 NVARCHAR (MAX)   NULL,
    [contactid]                          UNIQUEIDENTIFIER NULL,
    [address2_postalcode]                NVARCHAR (20)    NULL,
    [dfeta_addresslastupdated]           DATETIME         NULL,
    [dfeta_capitatrnchangedon]           DATETIME         NULL,
    [company]                            NVARCHAR (50)    NULL,
    [dfeta_ethnicityidname]              NVARCHAR (250)   NULL,
    [yomifirstname]                      NVARCHAR (150)   NULL,
    [address1_stateorprovince]           NVARCHAR (50)    NULL,
    [suffix]                             NVARCHAR (10)    NULL,
    [address2_utcoffset]                 INT              NULL,
    [lastusedincampaign]                 DATETIME         NULL,
    [address2_fax]                       NVARCHAR (50)    NULL,
    [preferredsystemuseridyominame]      NVARCHAR (100)   NULL,
    [address1_upszone]                   NVARCHAR (4)     NULL,
    [modifiedbyexternalpartyname]        NVARCHAR (100)   NULL,
    [address3_primarycontactname]        NVARCHAR (100)   NULL,
    [address1_telephone1]                NVARCHAR (50)    NULL,
    [address1_telephone2]                NVARCHAR (50)    NULL,
    [telephone1]                         NVARCHAR (60)    NULL,
    [address2_line2]                     NVARCHAR (250)   NULL,
    [dfeta_partyid]                      NVARCHAR (50)    NULL,
    [address1_addressid]                 UNIQUEIDENTIFIER NULL,
    [address3_postalcode]                NVARCHAR (20)    NULL,
    [spousesname]                        NVARCHAR (100)   NULL,
    [owneridname]                        NVARCHAR (100)   NULL,
    [address1_latitude]                  DECIMAL (38, 5)  NULL,
    [address2_composite]                 NVARCHAR (MAX)   NULL,
    [parentcontactidname]                NVARCHAR (100)   NULL,
    [createdonbehalfbyname]              NVARCHAR (100)   NULL,
    [stageid]                            UNIQUEIDENTIFIER NULL,
    [createdbyname]                      NVARCHAR (100)   NULL,
    [entityimage_url]                    NVARCHAR (200)   NULL,
    [modifiedonbehalfbyyominame]         NVARCHAR (100)   NULL,
    [address2_county]                    NVARCHAR (50)    NULL,
    [originatingleadidname]              NVARCHAR (100)   NULL,
    [externaluseridentifier]             NVARCHAR (50)    NULL,
    [lastonholdtime]                     DATETIME         NULL,
    [nickname]                           NVARCHAR (50)    NULL,
    [address1_name]                      NVARCHAR (200)   NULL,
    [address1_postofficebox]             NVARCHAR (20)    NULL,
    [description]                        NVARCHAR (MAX)   NULL,
    [businesscardattributes]             NVARCHAR (4000)  NULL,
    [address1_line2]                     NVARCHAR (250)   NULL,
    [timespentbymeonemailandmeetings]    NVARCHAR (1250)  NULL,
    [dfeta_ninumber]                     NVARCHAR (9)     NULL,
    [importsequencenumber]               INT              NULL,
    [lastname]                           NVARCHAR (100)   NULL,
    [dfeta_evolveid]                     NVARCHAR (50)    NULL,
    [timezoneruleversionnumber]          INT              NULL,
    [parentcontactidyominame]            NVARCHAR (100)   NULL,
    [address1_country]                   NVARCHAR (80)    NULL,
    [anniversary]                        DATETIME         NULL,
    [dfeta_husid]                        NVARCHAR (100)   NULL,
    [parent_contactidname]               NVARCHAR (160)   NULL,
    [address3_longitude]                 DECIMAL (38, 5)  NULL,
    [yomimiddlename]                     NVARCHAR (150)   NULL,
    [address3_name]                      NVARCHAR (200)   NULL,
    [fullname]                           NVARCHAR (160)   NULL,
    [firstname]                          NVARCHAR (100)   NULL,
    [dfeta_qtsdate]                      DATETIME         NULL,
    [salutation]                         NVARCHAR (100)   NULL,
    [accountidname]                      NVARCHAR (100)   NULL,
    [modifiedbyexternalpartyyominame]    NVARCHAR (100)   NULL,
    [slainvokedidname]                   NVARCHAR (100)   NULL,
    [dfeta_eytsdate]                     DATETIME         NULL,
    [dfeta_nationalityidname]            NVARCHAR (250)   NULL,
    [home2]                              NVARCHAR (50)    NULL,
    [assistantphone]                     NVARCHAR (50)    NULL,
    [msdyn_segmentid]                    UNIQUEIDENTIFIER NULL,
    [msdyn_segmentid_entitytype]         NVARCHAR (128)   NULL,
    [msdyn_segmentidname]                NVARCHAR (100)   NULL,
    CONSTRAINT [EPK[dbo]].[contact]]] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

