CREATE TABLE [dbo].[dfeta_sanction] (
    [Id]                                          UNIQUEIDENTIFIER NOT NULL,
    [SinkCreatedOn]                               DATETIME         NULL,
    [SinkModifiedOn]                              DATETIME         NULL,
    [statecode]                                   INT              NULL,
    [statuscode]                                  INT              NULL,
    [dfeta_spent]                                 BIT              NULL,
    [dfeta_conditionmet]                          BIT              NULL,
    [dfeta_personid]                              UNIQUEIDENTIFIER NULL,
    [dfeta_personid_entitytype]                   NVARCHAR (128)   NULL,
    [dfeta_sanctioncodeid]                        UNIQUEIDENTIFIER NULL,
    [dfeta_sanctioncodeid_entitytype]             NVARCHAR (128)   NULL,
    [modifiedonbehalfby]                          UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfby_entitytype]               NVARCHAR (128)   NULL,
    [owninguser]                                  UNIQUEIDENTIFIER NULL,
    [owninguser_entitytype]                       NVARCHAR (128)   NULL,
    [owningteam]                                  UNIQUEIDENTIFIER NULL,
    [owningteam_entitytype]                       NVARCHAR (128)   NULL,
    [createdby]                                   UNIQUEIDENTIFIER NULL,
    [createdby_entitytype]                        NVARCHAR (128)   NULL,
    [modifiedby]                                  UNIQUEIDENTIFIER NULL,
    [modifiedby_entitytype]                       NVARCHAR (128)   NULL,
    [owningbusinessunit]                          UNIQUEIDENTIFIER NULL,
    [owningbusinessunit_entitytype]               NVARCHAR (128)   NULL,
    [createdonbehalfby]                           UNIQUEIDENTIFIER NULL,
    [createdonbehalfby_entitytype]                NVARCHAR (128)   NULL,
    [ownerid]                                     UNIQUEIDENTIFIER NULL,
    [ownerid_entitytype]                          NVARCHAR (128)   NULL,
    [dfeta_confirmedby]                           NVARCHAR (100)   NULL,
    [modifiedbyyominame]                          NVARCHAR (100)   NULL,
    [createdbyname]                               NVARCHAR (100)   NULL,
    [dfeta_confirmationsofconditionsmetornotmet]  NVARCHAR (MAX)   NULL,
    [dfeta_sanctionid]                            UNIQUEIDENTIFIER NULL,
    [dfeta_sanctioncodeidname]                    NVARCHAR (450)   NULL,
    [versionnumber]                               BIGINT           NULL,
    [dfeta_noreappuntildate]                      DATETIME         NULL,
    [modifiedbyname]                              NVARCHAR (100)   NULL,
    [createdonbehalfbyyominame]                   NVARCHAR (100)   NULL,
    [owneridname]                                 NVARCHAR (100)   NULL,
    [importsequencenumber]                        INT              NULL,
    [dfeta_name]                                  NVARCHAR (450)   NULL,
    [modifiedonbehalfbyname]                      NVARCHAR (100)   NULL,
    [dfeta_sanctiondetails]                       NVARCHAR (MAX)   NULL,
    [createdon]                                   DATETIME         NULL,
    [owneridtype]                                 NVARCHAR (4000)  NULL,
    [modifiedonbehalfbyyominame]                  NVARCHAR (100)   NULL,
    [dfeta_establishmentoffencedetails]           NVARCHAR (MAX)   NULL,
    [overriddencreatedon]                         DATETIME         NULL,
    [createdonbehalfbyname]                       NVARCHAR (100)   NULL,
    [dfeta_confirmationofconditionsmetornotmeton] DATETIME         NULL,
    [owningbusinessunitname]                      NVARCHAR (160)   NULL,
    [dfeta_personidyominame]                      NVARCHAR (450)   NULL,
    [timezoneruleversionnumber]                   INT              NULL,
    [dfeta_startdate]                             DATETIME         NULL,
    [dfeta_personidname]                          NVARCHAR (160)   NULL,
    [modifiedon]                                  DATETIME         NULL,
    [createdbyyominame]                           NVARCHAR (100)   NULL,
    [dfeta_enddate]                               DATETIME         NULL,
    [owneridyominame]                             NVARCHAR (100)   NULL,
    [utcconversiontimezonecode]                   INT              NULL,
    CONSTRAINT [EPK[dbo]].[dfeta_sanction]]] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

