CREATE TABLE [dbo].[dfeta_mrapplication] (
    [Id]                                      UNIQUEIDENTIFIER NOT NULL,
    [SinkCreatedOn]                           DATETIME         NULL,
    [SinkModifiedOn]                          DATETIME         NULL,
    [statecode]                               INT              NULL,
    [statuscode]                              INT              NULL,
    [dfeta_eea_assessment1]                   INT              NULL,
    [dfeta_eea_assessment2]                   INT              NULL,
    [dfeta_route]                             INT              NULL,
    [dfeta_ni_inductionstatusdecision]        INT              NULL,
    [dfeta_eea_ficontact]                     INT              NULL,
    [dfeta_eea_eligibility]                   INT              NULL,
    [dfeta_sc_inductionstatusdecision]        INT              NULL,
    [dfeta_eea_applicationtype]               INT              NULL,
    [dfeta_qtsawarded]                        BIT              NULL,
    [dfeta_eea_declineschecked]               BIT              NULL,
    [dfeta_eea_eligibilityconfirmed]          BIT              NULL,
    [dfeta_eea_fiadditioninformationreceived] BIT              NULL,
    [dfeta_confirmationemailsent]             BIT              NULL,
    [dfeta_eea_imiresponsereceived]           BIT              NULL,
    [dfeta_completedinduction]                BIT              NULL,
    [dfeta_sc_awardqts]                       BIT              NULL,
    [dfeta_noneea_3rdpartyletterbeingsent]    BIT              NULL,
    [dfeta_ni_awardqts]                       BIT              NULL,
    [dfeta_onlinecheckallowed]                BIT              NULL,
    [dfeta_noneea_awardqts]                   BIT              NULL,
    [dfeta_sc_gtcsregistrationstatuschecked]  BIT              NULL,
    [dfeta_eea_assessor1id]                   UNIQUEIDENTIFIER NULL,
    [dfeta_eea_assessor1id_entitytype]        NVARCHAR (128)   NULL,
    [dfeta_personid]                          UNIQUEIDENTIFIER NULL,
    [dfeta_personid_entitytype]               NVARCHAR (128)   NULL,
    [owningteam]                              UNIQUEIDENTIFIER NULL,
    [owningteam_entitytype]                   NVARCHAR (128)   NULL,
    [dfeta_applicantid]                       UNIQUEIDENTIFIER NULL,
    [dfeta_applicantid_entitytype]            NVARCHAR (128)   NULL,
    [dfeta_declinereason2]                    UNIQUEIDENTIFIER NULL,
    [dfeta_declinereason2_entitytype]         NVARCHAR (128)   NULL,
    [createdonbehalfby]                       UNIQUEIDENTIFIER NULL,
    [createdonbehalfby_entitytype]            NVARCHAR (128)   NULL,
    [dfeta_eea_assessor2id]                   UNIQUEIDENTIFIER NULL,
    [dfeta_eea_assessor2id_entitytype]        NVARCHAR (128)   NULL,
    [dfeta_declinereason1]                    UNIQUEIDENTIFIER NULL,
    [dfeta_declinereason1_entitytype]         NVARCHAR (128)   NULL,
    [modifiedonbehalfby]                      UNIQUEIDENTIFIER NULL,
    [modifiedonbehalfby_entitytype]           NVARCHAR (128)   NULL,
    [owninguser]                              UNIQUEIDENTIFIER NULL,
    [owninguser_entitytype]                   NVARCHAR (128)   NULL,
    [modifiedby]                              UNIQUEIDENTIFIER NULL,
    [modifiedby_entitytype]                   NVARCHAR (128)   NULL,
    [dfeta_noneea_countryid]                  UNIQUEIDENTIFIER NULL,
    [dfeta_noneea_countryid_entitytype]       NVARCHAR (128)   NULL,
    [owningbusinessunit]                      UNIQUEIDENTIFIER NULL,
    [owningbusinessunit_entitytype]           NVARCHAR (128)   NULL,
    [createdby]                               UNIQUEIDENTIFIER NULL,
    [createdby_entitytype]                    NVARCHAR (128)   NULL,
    [dfeta_countryid]                         UNIQUEIDENTIFIER NULL,
    [dfeta_countryid_entitytype]              NVARCHAR (128)   NULL,
    [dfeta_noneea_countrystateid]             UNIQUEIDENTIFIER NULL,
    [dfeta_noneea_countrystateid_entitytype]  NVARCHAR (128)   NULL,
    [ownerid]                                 UNIQUEIDENTIFIER NULL,
    [ownerid_entitytype]                      NVARCHAR (128)   NULL,
    [dfeta_noneea_referencenumber]            NVARCHAR (100)   NULL,
    [createdbyyominame]                       NVARCHAR (100)   NULL,
    [createdbyname]                           NVARCHAR (100)   NULL,
    [createdonbehalfbyyominame]               NVARCHAR (100)   NULL,
    [dfeta_dateoffirstassessment]             DATETIME         NULL,
    [owneridtype]                             NVARCHAR (4000)  NULL,
    [modifiedon]                              DATETIME         NULL,
    [dfeta_countryidname]                     NVARCHAR (250)   NULL,
    [dfeta_personidyominame]                  NVARCHAR (450)   NULL,
    [dfeta_eea_declarationdate]               DATETIME         NULL,
    [dfeta_declinereason1name]                NVARCHAR (250)   NULL,
    [modifiedbyname]                          NVARCHAR (100)   NULL,
    [dfeta_noneea_countryidname]              NVARCHAR (250)   NULL,
    [dfeta_sc_qtsdatedecision]                DATETIME         NULL,
    [dfeta_mrapplicationid]                   UNIQUEIDENTIFIER NULL,
    [dfeta_ni_qtsdatedecision]                DATETIME         NULL,
    [modifiedonbehalfbyname]                  NVARCHAR (100)   NULL,
    [owneridyominame]                         NVARCHAR (100)   NULL,
    [dfeta_ni_gtcniregistrationno]            NVARCHAR (20)    NULL,
    [dfeta_eea_iminumber]                     NVARCHAR (100)   NULL,
    [dfeta_decisionnotes]                     NVARCHAR (MAX)   NULL,
    [owneridname]                             NVARCHAR (100)   NULL,
    [importsequencenumber]                    INT              NULL,
    [modifiedbyyominame]                      NVARCHAR (100)   NULL,
    [dfeta_applicantidyominame]               NVARCHAR (450)   NULL,
    [dfeta_eea_assessor2idname]               NVARCHAR (200)   NULL,
    [utcconversiontimezonecode]               INT              NULL,
    [modifiedonbehalfbyyominame]              NVARCHAR (100)   NULL,
    [dfeta_noneea_countrystateidname]         NVARCHAR (250)   NULL,
    [dfeta_name]                              NVARCHAR (250)   NULL,
    [timezoneruleversionnumber]               INT              NULL,
    [dfeta_enddate]                           DATETIME         NULL,
    [dfeta_eea_assessor1idname]               NVARCHAR (200)   NULL,
    [overriddencreatedon]                     DATETIME         NULL,
    [dfeta_personidname]                      NVARCHAR (160)   NULL,
    [owningbusinessunitname]                  NVARCHAR (160)   NULL,
    [dfeta_startdate]                         DATETIME         NULL,
    [createdon]                               DATETIME         NULL,
    [versionnumber]                           BIGINT           NULL,
    [dfeta_eea_declarationrenewalreviewdate]  DATETIME         NULL,
    [dfeta_applicantidname]                   NVARCHAR (160)   NULL,
    [dfeta_sc_registrationnumber]             NVARCHAR (50)    NULL,
    [dfeta_eea_assessor2idyominame]           NVARCHAR (200)   NULL,
    [dfeta_declinereason2name]                NVARCHAR (250)   NULL,
    [dfeta_eea_imidatesent]                   DATETIME         NULL,
    [createdonbehalfbyname]                   NVARCHAR (100)   NULL,
    [dfeta_eea_assessor1idyominame]           NVARCHAR (200)   NULL,
    CONSTRAINT [EPK[dbo]].[dfeta_mrapplication]]] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO

