CREATE TABLE [dbo].[dfeta_sanctioncode] (
    [Id]                                     NVARCHAR (50)  NOT NULL,
    [SinkCreatedOn]                          DATETIME2 (7)  NULL,
    [SinkModifiedOn]                         DATETIME2 (7)  NULL,
    [statecode]                              INT            NULL,
    [statuscode]                             INT            NULL,
    [dfeta_allreports]                       TINYINT        NULL,
    [dfeta_individualteacherreport]          NVARCHAR (50)  NULL,
    [dfeta_section128barringdirectionreport] NVARCHAR (50)  NULL,
    [dfeta_inductionfailreport]              NVARCHAR (50)  NULL,
    [dfeta_othereeamemberstatereport]        TINYINT        NULL,
    [dfeta_blockselfserviceaccess]           NVARCHAR (50)  NULL,
    [dfeta_prohibitedteacherreport]          NVARCHAR (50)  NULL,
    [dfeta_gtcsanctionreport]                NVARCHAR (50)  NULL,
    [createdonbehalfby]                      NVARCHAR (1)   NULL,
    [createdonbehalfby_entitytype]           NVARCHAR (1)   NULL,
    [modifiedonbehalfby]                     NVARCHAR (1)   NULL,
    [modifiedonbehalfby_entitytype]          NVARCHAR (1)   NULL,
    [createdby]                              NVARCHAR (50)  NULL,
    [createdby_entitytype]                   NVARCHAR (50)  NULL,
    [organizationid]                         NVARCHAR (50)  NULL,
    [organizationid_entitytype]              NVARCHAR (50)  NULL,
    [modifiedby]                             NVARCHAR (50)  NULL,
    [modifiedby_entitytype]                  NVARCHAR (50)  NULL,
    [modifiedbyyominame]                     NVARCHAR (50)  NULL,
    [createdbyname]                          NVARCHAR (1)   NULL,
    [modifiedon]                             DATETIME2 (7)  NULL,
    [dfeta_sanctioncodeid]                   NVARCHAR (50)  NULL,
    [modifiedbyname]                         NVARCHAR (1)   NULL,
    [createdonbehalfbyyominame]              NVARCHAR (1)   NULL,
    [modifiedonbehalfbyname]                 NVARCHAR (1)   NULL,
    [importsequencenumber]                   TINYINT        NULL,
    [createdon]                              DATETIME2 (7)  NULL,
    [modifiedonbehalfbyyominame]             NVARCHAR (1)   NULL,
    [versionnumber]                          INT            NULL,
    [overriddencreatedon]                    DATETIME2 (7)  NULL,
    [createdonbehalfbyname]                  NVARCHAR (1)   NULL,
    [timezoneruleversionnumber]              NVARCHAR (1)   NULL,
    [createdbyyominame]                      NVARCHAR (50)  NULL,
    [organizationidname]                     NVARCHAR (1)   NULL,
    [dfeta_name]                             NVARCHAR (200) NULL,
    [dfeta_value]                            NVARCHAR (50)  NULL,
    [utcconversiontimezonecode]              NVARCHAR (1)   NULL,
    [dfeta_restrictportalalertsharing]       TINYINT        NULL
);


GO

